checks:
  php:
    code_rating: true
    duplication: true

build:
  tests:
    override:
      - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'clover'

filter:
  excluded_paths:
    - src/EtherpadLite/Tests/*
    - features/*
