sudo: required

language: php
php:
  - 5.6
  - 7.0
  - 7.1

services:
  - docker

before_script:
  - docker pull systemli/etherpad-lite:1.6.1
  - docker run -d -p 127.0.0.1:9001:9001 systemli/etherpad-lite:1.6.1
  - composer install
script:
  - vendor/bin/phpunit
  - vendor/bin/behat -f progress
